#!/usr/bin/env bash
# script to install and configure nginx

sudo apt update 
sudo apt upgrade -y
sudo apt install nginx -y
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx reload
