#!/usr/bin/env bash
# This script is written in Bash and starts with the shebang line '#!/usr/bin/env bash',
# which tells the system to use the 'bash' interpreter to execute the script.

# The next line 'echo "$$"' prints the process ID (PID) of the current running script.
# The '$$' is a special variable in Bash that represents the PID of the current process.
# When you run the script, it will display the PID of the running script.

echo "$$"
