#!/usr/bin/env bash
# This script is written in Bash and starts with the shebang line '#!/usr/bin/env bash',
# which tells the system to use the 'bash' interpreter to execute the script.

# The script contains an infinite loop, created with the 'while true' statement.
# The loop will keep running indefinitely until it is interrupted or terminated.

# Inside the loop, the 'echo' command is used to print the message "To infinity and beyond".
# This message will be repeatedly printed to the terminal every 2 seconds (sleep 2) as specified by the 'sleep' command.

# The 'sleep' command pauses the execution of the script for the specified number of seconds (in this case, 2 seconds).
# So, after printing the message, the script will wait for 2 seconds before printing it again.


while true; do
    echo "To infinity and beyond"
    sleep 2
done
