#!/bin/bash

# Start the 4-to_infinity_and_beyond script in the background
./4-to_infinity_and_beyond &

# Store the PID of the last background process (4-to_infinity_and_beyond)
PID=$!

# Wait for any key press to continue
read -n 1 -s -r -p "Press any key to stop the process..."

# Send the termination signal to the process with the stored PID
kill $PID
