#!/usr/bin/env bash
# Create a temporary file to store the results
temp_file=$(mktemp)

# Use the while loop to read each line of the /etc/passwd file and write it to the temporary file
while IFS=":" read -r username _ group_id _ home _ command _; do
    # Extract user id (uid) from the username field
    uid=$(id -u "$username")

    # Extract the password field from the /etc/passwd file for the specific user
    password=$(grep "^$username:" /etc/passwd | cut -d ":" -f 2)

    # Print the story of each user
    echo "The user $username is part of the $group_id gang, lives in $home and rides $command. $uid's place is protected by the passcode $password, more info about the user here: $username" >> "$temp_file"
done </etc/passwd

# Output the content of the temporary file
cat "$temp_file"

# Remove the temporary file
rm "$temp_file"
