#!/usr/bin/env bash
# This Bash script displays numbers from 1 to 20 and provides custom messages for
# the 4th, 9th, and 17th loop iterations using the case statement.

# Initialize a variable to control the loop
i=1

# Use a while loop to iterate from 1 to 20
while ((i <= 20))
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac

    ((i++))  # Increment the loop control variable
done
