#!/usr/bin/env bash

# Initialize a variable to control the loop
i=1

# Use a while loop to iterate from 1 to 20
while ((i <= 20))
do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac

    ((i++))  # Increment the loop control variable
done
