#!/usr/bin/env bash
# This Bash script displays the content of the current directory in a list format.

# Use the for loop to iterate through the files in the current directory
for file in *
do
    # Check if the file is not hidden (doesn't start with a dot)
    if [[ $file != .* ]]
    then
        # Extract the part of the name after the first dash
        name=$(echo "$file" | cut -d '-' -f 2-)

        # Display the name
        echo "$name"
    fi
done
